#' Create a Data Frame for a Single "Box" Item
#'
#' `create_box_ODK` Helper function to create a single "box". Generates a single row of data representing a "box" with specified attributes.
#'
#' @param type Character. The type of the box. Default is "box".
#' @param value Character. Specifies the box's value, often a summary type like "boxplot_summary".
#' @param parameter_list Character. Parameters for the box, e.g., color or text, passed as a string.
#' @param variable Character. Name of the variable represented in the box.
#' @param row Integer. Row identifier for the box.
#'
#' @return A data frame with one row containing the specified box attributes.
create_box_ODK <- function(type = "box", value = "boxplot_summary",
                       parameter_list = NULL, variable = NULL,
                       row = 1) {
  return(data.frame(
    type = type,
    value = value,
    parameter_list = parameter_list,
    variable = variable,
    row = row
  ))
}

#' Generate Data Frame of Box Items from Metadata
#'
#' `create_from_type_ODK` processes metadata to create a data frame with "box" items for each row in the metadata, based on the type of data.
#'
#' @param metadata Data frame. Metadata to be processed, containing columns `type`, `label`, and `name`.
#' @param value Character. Default value for box items, typically used for "boxplot_summary" or other summary types.
#'
#' @return A data frame containing rows of box items, each representing metadata attributes.
create_from_type_ODK <- function(metadata = ODK_sample_survey_group, value = "boxplot_summary") {
  if (nrow(metadata) == 0) return(NULL)
  
  metadata %>%
    dplyr::mutate(
      value = dplyr::case_when(
        type %in% c("integer", "decimal") ~ "boxplot_summary",
        TRUE ~ "bar_table"
      ),
      parameter_list = paste0("text = \"", label, "\", colour = \"blue\""),
      variable = name,
      row = dplyr::row_number()
    ) %>%
    dplyr::rowwise() %>%
    dplyr::summarise(
      create_box_ODK(type = "box", value = value, parameter_list = parameter_list, variable = variable, row = row),
      .groups = 'drop'
    )
}

#' Generate Display Pages from Metadata Based on Group and Type
#'
#' `create_display_pages_from_metadata_ODK` filters metadata by group and type, then generates a display page as a data frame of box items.
#'
#' @param input_data Data frame. Input metadata, containing columns for `group`, `type`, `label`, and `name`.
#' @param output_data Data frame. Placeholder for processed output (unused in this function).
#' @param group_name Character. Name of the group to filter metadata by (e.g., "Identification").
#'
#' @return A data frame of display pages, each row representing a box item based on the specified metadata attributes.
create_display_pages_from_metadata_ODK <- function(input_data = ODK_sample_survey, output_data, group_name = "Identification") {
  # Filter based on type and group, then generate the display page
  input_data <- input_data %>%
    dplyr::filter(group == group_name, type %in% c("integer") | grepl("select_one|select_multiple", type))
  
  data_group <- create_from_type_ODK(input_data)
  return(data_group)
}

#' Generate Data List for Display in Excel Template
#'
#' This function generates a data list structured as an Excel template, with grouped and miscellaneous variables displayed
#' for creating tabs on a Shiny dashboard. It filters variables based on presence in both the form and dataset,
#' organises them into specified groups, and adds miscellaneous items as a separate tab if needed.
#'
#' @param input_data Data frame containing metadata of form variables, including their `name`, `type`, and `label`.
#' @param output_data Data frame containing the dataset, which includes variables to be checked against `input_data`.
#' 
#' @details
#' This function filters variables that are defined in the form but not present in the dataset and organises
#' the contents into groups for tabbed display. Variables without a specific group are organised under "miscellaneous."
#' The resulting list includes `contents`, a `main_page`, and individual display tabs for each group.
#' 
#' @return A list named `excel_template` structured as follows:
#'   - `contents`: A data frame with `name`, `type`, `ID`, and `icon` for each displayable group.
#'   - `main_page`: A hardcoded main page data frame.
#'   - Group-specific display tabs generated by `create_display_pages_from_metadata`.
#' @export
#'
#' @examples
#' # Assuming `ODK_sample_survey` and `ODK_sample_data` are loaded:
#' # result <- generate_data_list(input_data = ODK_sample_survey, output_data = ODK_sample_data)
#'
generate_data_list <- function(input_data, output_data) {
  
  # Step 1: Filter to variables that exist in both the form and the data
  # (excluding begin_group and end_group)
  our_variables <- intersect(names(output_data), input_data$name)
  input_data <- input_data %>%
    dplyr::mutate(
      check = dplyr::case_when(
        type %in% c("begin_group", "end_group") ~ 1,
        name %in% our_variables ~ 1,
        TRUE ~ 0
      )
    ) %>%
    dplyr::filter(check == 1) %>%
    dplyr::select(-check)
  
  # Step 2: Define groupings, filling NAs with the preceding "group" label, then mark miscellaneous for those in no group. This is to group into different tabs on the dashboard.
  input_data <- input_data %>%
    dplyr::mutate(
      group = dplyr::case_when(
        type == "begin_group" ~ label,
        type == "end_group" ~ "no_group",
        TRUE ~ NA_character_
      )
    ) %>%
    tidyr::fill(group) %>%
    dplyr::mutate(group = ifelse(group == "no_group" & type != "end_group", "misc", group))
  
  # Check if "misc" has entries; if so, add "misc" as a group row
  if ("misc" %in% input_data$group) {
    misc_row <- data.frame(type = "begin_group", name = "misc", label = "Miscellaneous Variables", group = "misc")
    input_data <- dplyr::bind_rows(input_data, misc_row)
  }
  
  # Step 3: Remove groups of size 1 (these are empty groups). We do not want an empty group on the dashboard as a tab.
  input_data <- input_data %>%
    dplyr::add_count(group, name = "group_size") %>%
    dplyr::filter(group_size > 1) %>%
    dplyr::select(-group_size)
  
  # Step 4: Create excel_template list and populate sections
  excel_template <- list()
  
  # The contents is built from `begin_group` labels
  data_bg <- dplyr::filter(input_data, type == "begin_group")
  excel_template$contents <- data.frame(
    name = data_bg$label,
    type = "Display",
    ID = data_bg$name,
    icon = ""
  )
  
  # Main page setup - this is currently just hard coded in
  excel_template$main_page <- data.frame(
    type = "value_box",
    value = "value_box_rows",
    parameter_list = "text = \"Total rows of output data\", colour = \"aqua\", icon = \"table\""
  )
  
  # Generate display tabs for each `begin_group` (and for misc?)
  display_tabs <- purrr::map(
    .x = data_bg$group,
    .f = ~ create_display_pages_from_metadata_ODK(input_data = input_data, output_data = output_data, group_name = .x)
  )
  
  # Set names and merge display_tabs into excel_template
  names(display_tabs) <- data_bg$name
  excel_template <- c(excel_template, display_tabs)
  
  return(excel_template)
}