#' Assert that a tag has specified properties
#'
#' This function is a version of the `tagAssert` function 
#' from the `shinydashboard` package. It checks if a tag has the 
#' specified properties, such as type and class.
#'
#' @param tag A tag object (e.g., a `div` or `span` created with Shiny functions).
#' @param type The expected type of the tag, like "div", "a", or "span". If `NULL`, the type is not checked.
#' @param class An expected HTML class. If `NULL`, the class is not checked.
#' @param allowUI If `TRUE` (the default), allows dynamic outputs generated by
#'   \code{\link[shiny]{uiOutput}} or \code{\link[shiny]{htmlOutput}}. When a
#'   dynamic output is provided, `tagAssert` won't try to validate the contents.
#' 
#' @details This function is from by the internal `tagAssert` function 
#' in the `shinydashboard` package, which performs similar validations on 
#' Shiny tag objects.
#'
#' @note Full credit to the `shinydashboard` package for the original implementation of this function.
#'
#' @references 
#' Shinydashboard package: \url{https://github.com/rstudio/shinydashboard}
#'
tag_assert <- function(tag, type = NULL, class = NULL, allowUI = TRUE) {
  if (!inherits(tag, "shiny.tag")) {
    print(tag)
    stop("Expected an object with class 'shiny.tag'.")
  }
  
  # Skip dynamic output elements
  if (allowUI &&
      (hasCssClass(tag, "shiny-html-output") ||
       hasCssClass(tag, "shinydashboard-menu-output"))) {
    return()
  }
  
  if (!is.null(type) && tag$name != type) {
    stop("Expected tag to be of type ", type)
  }
  
  if (!is.null(class)) {
    if (is.null(tag$attribs$class)) {
      stop("Expected tag to have class '", class, "'")
      
    } else {
      tagClasses <- strsplit(tag$attribs$class, " ")[[1]]
      if (!(class %in% tagClasses)) {
        stop("Expected tag to have class '", class, "'")
      }
    }
  }
}

#' Check if a Shiny tag has a specified CSS class
#'
#' This function is a version of the `hasCssClass` function 
#' from the `shinydashboard` package. It checks whether a 
#' `shiny.tag` object contains a specific CSS class.
#'
#' @param tag A `shiny.tag` object (e.g., a `div` or `span` created with Shiny functions).
#' @param class A character string specifying the CSS class to check for.
#' 
#' @return Returns `TRUE` if the `shiny.tag` object has the specified CSS class, `FALSE` otherwise.
#' 
#' @details This function is from the internal `hasCssClass` function 
#' in the `shinydashboard` package, which performs similar checks on 
#' Shiny tag objects.
#'
#' @keywords internal
#' @note Full credit to the `shinydashboard` package for the original implementation of this function.
#'
#' @references 
#' Shinydashboard package: \url{https://github.com/rstudio/shinydashboard}
#'
hasCssClass <- function(tag, class) {
  if (is.null(tag$attribs) || is.null(tag$attribs$class))
    return(FALSE)
  
  classes <- strsplit(tag$attribs$class, " +")[[1]]
  return(class %in% classes)
}